# Generated by Django 4.2.16 on 2024-10-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status_game',
            field=models.CharField(choices=[('available', 'available'), ('waiting', 'waiting'), ('playing', 'playing'), ('offline', 'offline')], default='offline', max_length=10),
        ),
    ]
