# Generated by Django 4.2.16 on 2024-10-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
