# Generated by Django 4.2.16 on 2024-10-12 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_player_is_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_login',
        ),
        migrations.AddField(
            model_name='player',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
