# Generated by Django 4.2.16 on 2024-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
