# Generated by Django 4.2.15 on 2024-09-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_player_name_1', models.CharField(max_length=100)),
                ('match_player_name_2', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('match_winner', models.CharField(max_length=100)),
                ('match_loser', models.CharField(max_length=100)),
                ('match_left_score', models.IntegerField()),
                ('match_right_score', models.IntegerField()),
            ],
        ),
    ]
