# Generated by Django 4.2.16 on 2024-10-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='match_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='match_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='match_left_score',
            new_name='left_score',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='match_loser',
            new_name='loser',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='match_player_name_1',
            new_name='player_name_1',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='match_player_name_2',
            new_name='player_name_2',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='match_right_score',
            new_name='right_score',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='match_winner',
            new_name='winner',
        ),
    ]
