# Generated by Django 4.2.16 on 2024-10-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_rename_match_date_matches_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
